export const catogory = [
  { id: 1, name: "Action" },
  { id: 2, name: "Comedy" },
  { id: 3, name: "Romance" },
  { id: 4, name: "Thriller" },
  { id: 5, name: "Horror" },
  { id: 6, name: "Drama" },
  { id: 7, name: "Fantasy" },
  { id: 8, name: "Sports" },
  { id: 9, name: "Epic" },
  { id: 10, name: "Splatter" },
  { id: 11, name: "Crime film" },
  { id: 12, name: "Animation" },

  { id: 13, name: "Science fiction" },
  { id: 14, name: "Adventure" },
  { id: 15, name: "History" },
  { id: 16, name: "Martial Arts" },
  { id: 17, name: "Short" },
  { id: 18, name: "Romantic comedy" },
  { id: 19, name: "Action/Adventure" },
  { id: 20, name: "Fantasy" },
  { id: 21, name: "Documentary" },
];
